import React from 'react'

import { Ubuntu } from 'next/font/google';

export const metadata = {
  title: 'Community Core',
  description: 'Generated by Next.js',
}

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
